package vn.com.flight.customerManagement;

import domainapp.basics.exceptions.ConstraintViolationException;
import domainapp.basics.model.meta.AttrRef;
import domainapp.basics.model.meta.DAssoc;
import domainapp.basics.model.meta.DAssoc.AssocEndType;
import domainapp.basics.model.meta.DAssoc.AssocType;
import domainapp.basics.model.meta.DAssoc.Associate;
import domainapp.basics.model.meta.DAttr;
import domainapp.basics.model.meta.DAttr.Type;
import domainapp.basics.model.meta.DClass;
import domainapp.basics.model.meta.DOpt;
import domainapp.basics.util.Tuple;

/**
 * A domain class whose objects are city names. This class is used as 
 * the <code>allowedValues</code> of the domain attributes of 
 * other domain classes (e.g. Customer.city).  
 * 
 * <p>Method <code>toString</code> overrides <code>Object.toString</code> to 
 * return the string representation of a city name which is expected by 
 * the application. 
 * 
 * @author G3-SS207
 *
 */
@DClass(schema="FLIGHT")
public class City {

  
  public static final String A_name = "name";
  @DAttr(name="id",id=true,auto=true,length=3,mutable=false,optional=false,type=Type.Integer)
  private int id;
//static variable to keep track of city id
  private static int idCounter;
  
  @DAttr(name=A_name,type=Type.String,length=20,optional=false,cid=true)
  private String name;

  
  @DAttr(name="customer",type=Type.Domain,serialisable=false)
  @DAssoc(ascName="customer-has-city",role="city",
  ascType=AssocType.One2One, endType=AssocEndType.Many,
  associate=@Associate(type=Customer.class,cardMin=1,cardMax=1,determinant=true))
  private Customer customer;
  


  // from object form: customer is not included 
  @DOpt(type=DOpt.Type.ObjectFormConstructor)
  @DOpt(type=DOpt.Type.RequiredConstructor)
  public City(@AttrRef("name") String cityName) 
  {
    this(null, cityName);
  }

  // from object form: Customer is included
  @DOpt(type=DOpt.Type.ObjectFormConstructor)
  public City(@AttrRef("name") String cityName, @AttrRef("customer") Customer customer) 
  {
    this(null, cityName, customer);
  }

  // from data source
  @DOpt(type=DOpt.Type.DataSourceConstructor)
  public City(@AttrRef("id") Integer id, @AttrRef("name") String cityName) 
  {
    this(id, cityName,null);
  }
  
  // based constructor (used by others)
  private City(Integer id, String cityName, Customer customer) 
  {
    this.id = nextId(id);
    this.name = cityName;
    this.customer = customer;
  }
  

private static int nextId(Integer currID) 
{
    if (currID == null) 
    {
      idCounter++;
      return idCounter;
    } else {
      int num = currID.intValue();
      if (num > idCounter)
        idCounter = num;
      
      return currID;
    }
  }

  /**
   * @requires 
   *  minVal != null /\ maxVal != null
   * @effects 
   *  update the auto-generated value of attribute <tt>attrib</tt>, specified for <tt>derivingValue</tt>, using <tt>minVal, maxVal</tt>
   */
  @DOpt(type=DOpt.Type.AutoAttributeValueSynchroniser)
  public static void updateAutoGeneratedValue(
      DAttr attrib,
      Tuple derivingValue, 
      Object minVal, 
      Object maxVal) throws ConstraintViolationException 
  {
    
    if (minVal != null && maxVal != null) 
    {
      //TODO: update this for the correct attribute if there are more than one auto attributes of this class 
      int maxIdVal = (Integer) maxVal;
      if (maxIdVal > idCounter)  
        idCounter = maxIdVal;
    }
  }
  
  

public int getId() 
{
    return id;
  }
  
  public String getName() 
  {
    return name;
  }
  
  public void setName(String name) 
  {
    this.name = name;
  }

  public Customer getCustomer() 
  {
    return customer;
  }


  @DOpt(type=DOpt.Type.LinkAdderNew)
  public void setNewCustomer(Customer customer) 
  {
    this.customer = customer;
    // do other updates here (if needed)
  }

  public void setCustomer(Customer customer) 
  {
    this.customer = customer;
  }


  @Override
  public String toString() 
  {
    return name ;
  }
}
