package vn.com.flight.flightManagement;

import domainapp.basics.exceptions.ConstraintViolationException;
import domainapp.basics.model.meta.AttrRef;
import domainapp.basics.model.meta.DAssoc;
import domainapp.basics.model.meta.DAttr;
import domainapp.basics.model.meta.DClass;
import domainapp.basics.model.meta.DOpt;
import domainapp.basics.model.meta.DAssoc.AssocEndType;
import domainapp.basics.model.meta.DAssoc.AssocType;
import domainapp.basics.model.meta.DAssoc.Associate;
import domainapp.basics.model.meta.DAttr.Type;
import domainapp.basics.util.Tuple;

@DClass(schema="FLIGHT")
public class Airplane {
	  @DAttr(name="id",id=true,auto=true,length=3,mutable=false,optional=false,type=Type.Integer)
	  private int id;
	//static variable to keep track of airplane id
	  private static int idCounter;
	  
	  @DAttr(name="model",type=Type.String,length=20,optional=false,cid=true)
	  private String model;
	  
	  @DAttr(name="PlaneSerialNumber",type=Type.String,length=20,optional=false)
	  private String PlaneSerialNumber;
	  
	  @DAttr(name="seat",type=Type.Integer,length=20,optional=false)
	  private int seat;
//	  
//	  @DAttr(name = "airplane", type = Type.Domain, length = 20, optional = true)
//	  @DAssoc(ascName="flight-has-airplane",role="flight",
//	      ascType=AssocType.One2Many, endType=AssocEndType.Many,
//	  associate=@Associate(type=Flight.class,cardMin=1,cardMax=10))
//	  private Flight flight;
	  
	  @DOpt(type=DOpt.Type.ObjectFormConstructor)
	  @DOpt(type=DOpt.Type.RequiredConstructor)
	  public Airplane(@AttrRef("model") String model, 
			  @AttrRef("PlaneSerialNumber") String PlaneSerialNumber,
			  @AttrRef("seat") Integer seat) 
	  {
	    this(null, model, PlaneSerialNumber,seat);
	  }
	  public Airplane(Integer id, String model, String PlaneSerialNumber, Integer seat) 
	  {
		    this.id = nextId(id);
		    this.model = model;
		    this.PlaneSerialNumber = PlaneSerialNumber;
		    this.seat = seat; 
	  }
	  
	  
	public String getModel() 
	{
		return model;
	}
	public void setModel(String model) 
	{
		this.model = model;
	}
	public String getPlaneSerialNumber() 
	{
		return PlaneSerialNumber;
	}
	public void setPlaneSerialNumber(String planeSerialNumber) 
	{
		PlaneSerialNumber = planeSerialNumber;
	}
	public int getSeat() throws Exception 
	{
		if(seat < 1) 
		{
			throw new Exception("INVALID SEAT");
		} else {
		return seat;
	}
	}
	public void setSeat(int seat) 
	{
		this.seat = seat;
	}
	public int getId() 
	{
		return id;
	}
	
	
	private static int nextId(Integer currID) 
	{
		    if (currID == null) 
		    {
		      idCounter++;
		      return idCounter;
		    } else {
		      int num = currID.intValue();
		      if (num > idCounter)
		        idCounter = num;
		      
		      return currID;
		    }
	}
	  /**
	   * @requires 
	   *  minVal != null /\ maxVal != null
	   * @effects 
	   *  update the auto-generated value of attribute <tt>attrib</tt>, specified for <tt>derivingValue</tt>, using <tt>minVal, maxVal</tt>
	   */
	  @DOpt(type=DOpt.Type.AutoAttributeValueSynchroniser)
	  public static void updateAutoGeneratedValue(
	      DAttr attrib,
	      Tuple derivingValue, 
	      Object minVal, 
	      Object maxVal) throws ConstraintViolationException 
	  {
	    
	    if (minVal != null && maxVal != null) {
	      //TODO: update this for the correct attribute if there are more than one auto attributes of this class 
	      int maxIdVal = (Integer) maxVal;
	      if (maxIdVal > idCounter)  
	        idCounter = maxIdVal;
	    }
	  }
	  @Override
	  public String toString() 
	  {
	    return model ;
	  }
	  
	  
}
